permissionset 50100 MyAppPermissions
{
    Assignable = true;
    Permissions = tabledata "Group Master" = RIMD,
  tabledata "Integration Logs" = RIMD,
        table "Group Master" = X,
   table "Integration Logs" = X,
        codeunit OrderProcessing = X,
        codeunit SalesQuoteWebToBC = X,
        page "Group Master Lists" = X,
        tabledata Application = RIMD,
        tabledata "Application Sub-Segment" = RIMD,
        tabledata Industry = RIMD,
        tabledata "Industry Sub-Segment" = RIMD,
        table Application = X,
        table "Application Sub-Segment" = X,
        table Industry = X,
        table "Industry Sub-Segment" = X,
        report CustomSalesOrder = X,
        page "Application Master" = X,
        page "Application Subsegement Master" = X,
        page "Industry Master" = X,
        page "Industry SubSegment" = X,
        report CustomPurchaseOrder = X,
        tabledata "Delivery Terms" = RIMD,
        tabledata "Freight Term" = RIMD,
        tabledata "Gst Rate Percentage" = RIMD,
        table "Delivery Terms" = X,
        table "Freight Term" = X,
        table "Gst Rate Percentage" = X,
        page "Delivery Terms Lists" = X,
        page "Freight Term Lists" = X,
        page "GST Rate %" = X,
        tabledata "Business Sector" = RIMD,
        table "Business Sector" = X,
        codeunit UserAuthentication = X,
        page "Business Sector List" = X,
        tabledata "No Series for Purchase" = RIMD,
        tabledata "No Series for Sales" = RIMD,
        table "No Series for Purchase" = X,
        table "No Series for Sales" = X,
        page "No Series Selection for Purch" = X,
        page "No Series Selection for Sales" = X,
        tabledata "Instrument Sales Header" = RIMD,
        tabledata "Instrument Sales Line" = RIMD,
        tabledata "Sales Order Type" = RIMD,
        table "Instrument Sales Header" = X,
        table "Instrument Sales Line" = X,
        table "Sales Order Type" = X,
        page "Sales Order Type List" = X,
        table "Location" = X,

        tabledata "Rate Per KM" = RIMD,
        table "Rate Per KM" = X,
        page "Rate Per KM" = X,
        tabledata "Expense Voucher Header" = RIMD,
        tabledata "Expense Voucher Line" = RIMD,
        tabledata "Mode/Class Jrn" = RIMD,
        table "Mode/Class Jrn" = x,
        table "Expense Voucher Header" = X,
        table "Expense Voucher Line" = X,
        page "Mode/Class Jrn List" = x,

tabledata "TripGain Voucher Header" = RIMD,
        tabledata "TripGain Voucher Line" = RIMD,
        table "TripGain Voucher Header" = X,
        table "TripGain Voucher Line" = X,

        tabledata "Default Dimension" = RIMD,
        table "Default Dimension" = x,
        tabledata "Dimension Value" = RIMD,
        table "Dimension Value" = x,
        tabledata ServiceType = RIMD,
        table ServiceType = x,
        tabledata "Service Description" = RIMD,
        table "Service Description" = x,
        tabledata "Custom Duty Setup" = RIMD,
        table "Custom Duty Setup" = x;

}
